apiVersion: v1
kind: Service
metadata:
  labels:
    app: version-hello
    app.kubernetes.io/component: version-hello
    app.kubernetes.io/instance: version-hello
  name: version-hello
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    deployment: version-hello
  sessionAffinity: None
  type: ClusterIP
